name: HeySOS

# =====================================================================
# xcodegen spec — https://github.com/yonaskolb/XcodeGen
# Run: xcodegen generate
# =====================================================================

options:
  bundleIdPrefix: com.heysos
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16"
  defaultConfig: Debug
  groupSortPosition: top
  indentWidth: 4
  tabWidth: 4
  generateEmptyDirectories: false

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ALWAYS_SEARCH_USER_PATHS: NO

configs:
  Debug: debug
  Release: release

# =====================================================================
# Targets
# =====================================================================

targets:

  # -------------------------------------------------------------------
  # Main App Target
  # -------------------------------------------------------------------
  HeySOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"

    sources:
      - path: Sources
        excludes:
          - Resources/Binaries/**   # binaries are bundled via resources, not compiled
          - "**/.DS_Store"

    resources:
      - path: Sources/Resources/Assets.xcassets
      - path: Sources/Resources/Binaries
        buildPhase: resources

    entitlements:
      path: Sources/Resources/HeySOS.entitlements

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.heysos.app
        PRODUCT_NAME: HeySOS
        SWIFT_VERSION: "5.9"

        # Info.plist — auto-generated by Xcode build system (Xcode 13+)
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: HeySOS
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 HeySOS Contributors. GPLv3."
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_NSPrincipalClass: NSApplication

        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"

        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

        # Hardened Runtime (required for notarization)
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Sources/Resources/HeySOS.entitlements

        # Architecture: universal binary
        ARCHS: "$(ARCHS_STANDARD)"
        ONLY_ACTIVE_ARCH: YES

      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES
          DEBUG_INFORMATION_FORMAT: dwarf
          ENABLE_TESTABILITY: YES
          # Allow building without signing locally
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGNING_ALLOWED: NO

        Release:
          ONLY_ACTIVE_ARCH: NO          # build universal (arm64 + x86_64)
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
          SWIFT_COMPILATION_MODE: wholemodule
          ENABLE_NS_ASSERTIONS: NO
          CODE_SIGN_STYLE: Automatic

  # -------------------------------------------------------------------
  # Unit Test Target
  # -------------------------------------------------------------------
  HeySOS-Tests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"

    sources:
      - Tests

    dependencies:
      - target: HeySOS

    settings:
      base:
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.heysos.app.tests
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO

# =====================================================================
# Schemes
# =====================================================================

schemes:
  HeySOS:
    build:
      targets:
        HeySOS: all
        HeySOS-Tests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - HeySOS-Tests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
